-- =====================================================================
-- MIENRA Web - Schema relationnel
--
-- Ce fichier a ete remplace par une version plus compatible avec Supabase
-- SQL Editor, notamment pour les policies RLS et les colonnes legacy_id
-- necessaires a la migration depuis l'ancien stockage JSON.
--
-- Utiliser maintenant :
--   supabase/relational-schema-compatible.sql
--
-- Puis, si des donnees existent deja dans mienra_app_state :
--   supabase/migrate-json-to-relational.sql
-- =====================================================================

-- Fichier volontairement non destructif.
-- Il ne cree rien et ne modifie rien afin d'eviter toute confusion.
